### ISSUE TITLE
selenium 3.0 support

### ISSUE THREAD

**Issue by grawk** [paypal/nemo-core#136]
at least some changes will be required within nemo, and possibly within plugins, to support selenium@3.

**Comment by grawk** [comment]
Node >= v6 will be required.

**Comment by grawk** [comment]
PromiseManager is being phased out. This is likely to impact how we want to implement our various plugins: https://github.com/SeleniumHQ/selenium/issues/2969

**Comment by manoj9788** [comment]
@grawk  I can help with this soon !!

**Comment by jonathansamines** [comment]
@grawk @manoj9788 I would like to help to get this working, now that Node 8 LTS is out there 🐱

**Comment by grawk** [comment]
this is done

**Comment by manoj9788** [comment]
Good work! @grawk
