### ISSUE TITLE
Not able to set the chromeOptions flags for chromedriver when building driver

### ISSUE THREAD

**Issue by amogh92dr** [paypal/nemo-core#169]
I am not able to set chromeOptions flag ('--start-maximized','--incognito','--use-fake-ui-for-media-stream') correctly in the config file. Can someone give me any example of how I can make this work?

**Comment by skratchdot** [comment]
Something like this should work:
```
{
  "driver": {
    "browser": "chrome",
    "builders": {
      "forBrowser": [
        "chrome"
      ],
      "withCapabilities": [{
        "browserName": "chrome",
        "chromeOptions": {
          "args": [
            "start-maximized", "incognito", "use-fake-ui-for-media-stream"
          ]
        }
      }]
    }
  }
}
```

**Comment by skratchdot** [comment]
A simpler example from the docs:
https://github.com/paypal/nemo-docs/blob/master/faq.md#passing-chrome-commandline-arguments
