### ISSUE TITLE
Add Page Object support for Nemo

### ISSUE THREAD

**Issue by gkushang** [paypal/nemo-core#83]
This could be a plugin where user can define path to Page object, e.g. `tests/functional/pages` and can access pages with the nemo `nemo.page.login` and access all the page related methods.

**Comment by gkushang** [comment]
@grawk let me know what you think about this. Please share your thoughts as well. I'd be happy to work on this.

**Comment by grawk** [comment]
Can you fill in some more detail on what a "page object" is? I feel like I should know but I don't :(

**Comment by gkushang** [comment]
Sure. The page object abstracts the underlying webElements/Html actions to manipulate the page, and helps to wrap the UI elements per page into the page object. We have implemented page object for our project [here] (https://github.paypal.com/Identity-R/authnodeweb/tree/develop/tests/acceptance/pages), but I still feel it can be much better if nemo can maintain these pages. Basically, tests do not need to know the elements but knows only the Page and its methods. I'll be happy to discuss more with you, please let me know.

**Comment by grawk** [comment]
@gkushang have you seen the `nemo-page` plugin? Perhaps that can satisfy this requirement? https://www.npmjs.com/package/nemo-page

**Comment by grawk** [comment]
Can we address page objects using plugin and examples as mentioned above?
